### ISSUE TITLE
Problems with example

### ISSUE THREAD

**Issue by popovae** [Akkyie/AKPickerView#29] opened 2014-12-24 09:54 UTC
Hello! First of all I want to thank you for such a great work!

Now I have a small problem I cant figure out. I copied the example ViewController to my project, created a new view and etc. Everything works fine except two things:

1) I always get the errors in NSLog (from didSelectItem: method):
2014-12-23 20:58:29.569 XXX[21526:807229] the behavior of the UICollectionViewFlowLayout is not defined because:
2014-12-23 20:58:29.569 XXXX[21526:807229] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values.
2014-12-23 20:58:29.570 XXXXX[21526:807229] Please check the values return by the delegate.

2) The last item in the created view is always below the others...(see screenshot below)
![screen shot 2014-12-24 at 10 52 16](https://cloud.githubusercontent.com/assets/6538329/5547508/f5635936-8b5a-11e4-9c4f-6c2cb6adbd5a.JPEG)

What can be possibly be wrong? I cant figure it put for already two days))

**Comment by iOSDeveloperSK** [comment] 2015-03-23 17:51
Hi, I have problem with scrolling. I set the datasouce:

let data = [
                    "blank","0","1","2","3","4","5","6",
                    "7","8","9","\u{0022}", "\u{005C}", "§","&","@",
                    "#","$","€","£","¢","¥","฿","(",
                    ")","]","[","{","}",">","<","~",
                    "’",".",";",":",",","–","+","±",
                    "*","/","_","|","%","≥","≤","‹",
                    "›","°","»","”","?","¿","!","¡",
                    "😃","😀","😊","☺️","😉","😍","😘","😚",
                    "😗","😙","😜","😝","😛","😳","😁","😔",
                    "😌","😒","😞","😣","😢","😂","😭","😪",
                    "😥","😰","😅","😓","😩","😫","😨","😱",
                    "😠","😡","😤","😖","😆","😋","😷","😎",
                    "😴","😵","😲","😟","😦","😧","😮","😬",
                    "😐","😕","😯","😶","😇","😏","😑","❤️",
                    "💔","💋","💘","💞","💌","👍","👌","👎",
                    "☀︎","☼","☽","☁︎","☂","★","☆","✈︎","⚽︎",
                    "👊","✌️"
                    ]
Scrolling is delayed (if you scroll more time, and is not working properly). And the app (thread) is blocked for a long time. Could you solve this problem and try to make this app async? 
Thanks.

**Comment by Akkyie** [comment] 2015-03-24 22:31
I tested, and it actually happens. But could you recreate a issue on [AKPickerView-Swift](https://github.com/Akkyie/AKPickerView-Swift/issues)?

**Comment by Akkyie** [comment] 2015-03-24 22:32
@iOSDeveloperSK I tested, and it actually happens. But could you recreate a issue on [AKPickerView-Swift](https://github.com/Akkyie/AKPickerView-Swift/issues)?

**Comment by Akkyie** [comment] 2015-03-24 22:34
And I couldn't reproduce @popovae 's problem after all. So I'm closing this issue, but any additional information are welcomed.

**Closed by Akkyie** 2015-03-24 22:34 UTC
Labels: bug

**Comment by sseyod** [comment] 2015-06-30 10:57
Hi! 

Thanks for a great project - especially for the Swift version! :)

Just in case you're interested, the way to reproduce the problem where the second view was always below the others, is that you see the reported behaviour when you also see this message "behavior of the UICollectionViewFlowLayout is not defined because" ...

If you change the code to get rid of that warning message, like this Swift code:

```
  override func viewDidLoad() {
    super.viewDidLoad()
   
    // Advice from https://github.com/Akkyie/AKPickerView-Swift/issues/8
    self.automaticallyAdjustsScrollViewInsets = true
```

Then the problem disappears. I guess it must just be a problem with iOS.

Hope that helps!

Pete

**Comment by Akkyie** [comment] 2015-07-04 00:11
@sseyod Thank you for your cooperation!
